### ISSUE TITLE
Missing feedback for submission 5549

### ISSUE THREAD

**Issue by ChristianFrisson** [fosdem-testingautomation/room-materials#4]
Dear R. Tyler Croy and Jeff Weiss,

I have not yet received feedback from my submission to your devroom about [InspectorWidget](https://github.com/InspectorWidget):
https://penta.fosdem.org/submission/FOSDEM17/event/5549

On December 13, I have sent an email to R. Tyler only (since it was the only email address mentioned in the call for participation) to double-check if my submission was properly received, but I did not receive any confirmation.
https://lists.fosdem.org/pipermail/fosdem/2016-October/002491.html

Looking forward to reaching you through this issue,
Christian

**Comment by rtyler** [comment]
@ChristianFrisson Sorry for the radio silence, all communications have now been sent out. I try to avoid responding with status to people who email me one-off because I think that's unfair to the other submitters.

**Comment by ChristianFrisson** [comment]
OK thanks for the clarification!
